# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nathan/projects/c++/TardigradeRenderEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nathan/projects/c++/TardigradeRenderEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-bin\" \"assimp-dev\" \"libassimp5.0.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/projects/c++/TardigradeRenderEngine/CMakeFiles /home/nathan/projects/c++/TardigradeRenderEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/projects/c++/TardigradeRenderEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RenderEngine

# Build rule for target.
RenderEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RenderEngine
.PHONY : RenderEngine

# fast build rule for target.
RenderEngine/fast:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/build
.PHONY : RenderEngine/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f external/glfw-3.3.2/CMakeFiles/uninstall.dir/build.make external/glfw-3.3.2/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f external/glfw-3.3.2/src/CMakeFiles/glfw.dir/build.make external/glfw-3.3.2/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named boing

# Build rule for target.
boing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boing
.PHONY : boing

# fast build rule for target.
boing/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/boing.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/boing.dir/build
.PHONY : boing/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/gears.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named heightmap

# Build rule for target.
heightmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heightmap
.PHONY : heightmap

# fast build rule for target.
heightmap/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/heightmap.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/heightmap.dir/build
.PHONY : heightmap/fast

#=============================================================================
# Target rules for targets named sharing

# Build rule for target.
sharing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sharing
.PHONY : sharing

# fast build rule for target.
sharing/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/sharing.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/sharing.dir/build
.PHONY : sharing/fast

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/particles.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/simple.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named splitview

# Build rule for target.
splitview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 splitview
.PHONY : splitview

# fast build rule for target.
splitview/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/splitview.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/splitview.dir/build
.PHONY : splitview/fast

#=============================================================================
# Target rules for targets named offscreen

# Build rule for target.
offscreen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 offscreen
.PHONY : offscreen

# fast build rule for target.
offscreen/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/offscreen.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/offscreen.dir/build
.PHONY : offscreen/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) -f external/glfw-3.3.2/examples/CMakeFiles/wave.dir/build.make external/glfw-3.3.2/examples/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named triangle-vulkan

# Build rule for target.
triangle-vulkan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle-vulkan
.PHONY : triangle-vulkan

# fast build rule for target.
triangle-vulkan/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/triangle-vulkan.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/triangle-vulkan.dir/build
.PHONY : triangle-vulkan/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/tearing.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/title.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named opacity

# Build rule for target.
opacity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opacity
.PHONY : opacity

# fast build rule for target.
opacity/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/opacity.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/opacity.dir/build
.PHONY : opacity/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/clipboard.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named msaa

# Build rule for target.
msaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msaa
.PHONY : msaa

# fast build rule for target.
msaa/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/msaa.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/msaa.dir/build
.PHONY : msaa/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/glfwinfo.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/iconify.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/reopen.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/gamma.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named monitors

# Build rule for target.
monitors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monitors
.PHONY : monitors

# fast build rule for target.
monitors/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/monitors.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/monitors.dir/build
.PHONY : monitors/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/windows.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

#=============================================================================
# Target rules for targets named timeout

# Build rule for target.
timeout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timeout
.PHONY : timeout

# fast build rule for target.
timeout/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/timeout.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/timeout.dir/build
.PHONY : timeout/fast

#=============================================================================
# Target rules for targets named inputlag

# Build rule for target.
inputlag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inputlag
.PHONY : inputlag

# fast build rule for target.
inputlag/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/inputlag.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/inputlag.dir/build
.PHONY : inputlag/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/threads.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named cursor

# Build rule for target.
cursor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cursor
.PHONY : cursor

# fast build rule for target.
cursor/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/cursor.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/cursor.dir/build
.PHONY : cursor/fast

#=============================================================================
# Target rules for targets named empty

# Build rule for target.
empty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 empty
.PHONY : empty

# fast build rule for target.
empty/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/empty.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/empty.dir/build
.PHONY : empty/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/icon.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/events.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) -f external/glfw-3.3.2/tests/CMakeFiles/joysticks.dir/build.make external/glfw-3.3.2/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f external/GLAD/CMakeFiles/glad.dir/build.make external/GLAD/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named IrrXML

# Build rule for target.
IrrXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IrrXML
.PHONY : IrrXML

# fast build rule for target.
IrrXML/fast:
	$(MAKE) -f external/assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build.make external/assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build
.PHONY : IrrXML/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f external/assimp/code/CMakeFiles/assimp.dir/build.make external/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named assimp_cmd

# Build rule for target.
assimp_cmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp_cmd
.PHONY : assimp_cmd

# fast build rule for target.
assimp_cmd/fast:
	$(MAKE) -f external/assimp/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build.make external/assimp/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build
.PHONY : assimp_cmd/fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit
.PHONY : unit

# fast build rule for target.
unit/fast:
	$(MAKE) -f external/assimp/test/CMakeFiles/unit.dir/build.make external/assimp/test/CMakeFiles/unit.dir/build
.PHONY : unit/fast

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Controls.o: src/Controls.cpp.o

.PHONY : src/Controls.o

# target to build an object file
src/Controls.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Controls.cpp.o
.PHONY : src/Controls.cpp.o

src/Controls.i: src/Controls.cpp.i

.PHONY : src/Controls.i

# target to preprocess a source file
src/Controls.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Controls.cpp.i
.PHONY : src/Controls.cpp.i

src/Controls.s: src/Controls.cpp.s

.PHONY : src/Controls.s

# target to generate assembly for a file
src/Controls.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Controls.cpp.s
.PHONY : src/Controls.cpp.s

src/Cube.o: src/Cube.cpp.o

.PHONY : src/Cube.o

# target to build an object file
src/Cube.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Cube.cpp.o
.PHONY : src/Cube.cpp.o

src/Cube.i: src/Cube.cpp.i

.PHONY : src/Cube.i

# target to preprocess a source file
src/Cube.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Cube.cpp.i
.PHONY : src/Cube.cpp.i

src/Cube.s: src/Cube.cpp.s

.PHONY : src/Cube.s

# target to generate assembly for a file
src/Cube.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Cube.cpp.s
.PHONY : src/Cube.cpp.s

src/CubeMap.o: src/CubeMap.cpp.o

.PHONY : src/CubeMap.o

# target to build an object file
src/CubeMap.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/CubeMap.cpp.o
.PHONY : src/CubeMap.cpp.o

src/CubeMap.i: src/CubeMap.cpp.i

.PHONY : src/CubeMap.i

# target to preprocess a source file
src/CubeMap.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/CubeMap.cpp.i
.PHONY : src/CubeMap.cpp.i

src/CubeMap.s: src/CubeMap.cpp.s

.PHONY : src/CubeMap.s

# target to generate assembly for a file
src/CubeMap.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/CubeMap.cpp.s
.PHONY : src/CubeMap.cpp.s

src/Group.o: src/Group.cpp.o

.PHONY : src/Group.o

# target to build an object file
src/Group.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Group.cpp.o
.PHONY : src/Group.cpp.o

src/Group.i: src/Group.cpp.i

.PHONY : src/Group.i

# target to preprocess a source file
src/Group.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Group.cpp.i
.PHONY : src/Group.cpp.i

src/Group.s: src/Group.cpp.s

.PHONY : src/Group.s

# target to generate assembly for a file
src/Group.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Group.cpp.s
.PHONY : src/Group.cpp.s

src/ImGui/imgui.o: src/ImGui/imgui.cpp.o

.PHONY : src/ImGui/imgui.o

# target to build an object file
src/ImGui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui.cpp.o
.PHONY : src/ImGui/imgui.cpp.o

src/ImGui/imgui.i: src/ImGui/imgui.cpp.i

.PHONY : src/ImGui/imgui.i

# target to preprocess a source file
src/ImGui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui.cpp.i
.PHONY : src/ImGui/imgui.cpp.i

src/ImGui/imgui.s: src/ImGui/imgui.cpp.s

.PHONY : src/ImGui/imgui.s

# target to generate assembly for a file
src/ImGui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui.cpp.s
.PHONY : src/ImGui/imgui.cpp.s

src/ImGui/imgui_demo.o: src/ImGui/imgui_demo.cpp.o

.PHONY : src/ImGui/imgui_demo.o

# target to build an object file
src/ImGui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_demo.cpp.o
.PHONY : src/ImGui/imgui_demo.cpp.o

src/ImGui/imgui_demo.i: src/ImGui/imgui_demo.cpp.i

.PHONY : src/ImGui/imgui_demo.i

# target to preprocess a source file
src/ImGui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_demo.cpp.i
.PHONY : src/ImGui/imgui_demo.cpp.i

src/ImGui/imgui_demo.s: src/ImGui/imgui_demo.cpp.s

.PHONY : src/ImGui/imgui_demo.s

# target to generate assembly for a file
src/ImGui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_demo.cpp.s
.PHONY : src/ImGui/imgui_demo.cpp.s

src/ImGui/imgui_draw.o: src/ImGui/imgui_draw.cpp.o

.PHONY : src/ImGui/imgui_draw.o

# target to build an object file
src/ImGui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_draw.cpp.o
.PHONY : src/ImGui/imgui_draw.cpp.o

src/ImGui/imgui_draw.i: src/ImGui/imgui_draw.cpp.i

.PHONY : src/ImGui/imgui_draw.i

# target to preprocess a source file
src/ImGui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_draw.cpp.i
.PHONY : src/ImGui/imgui_draw.cpp.i

src/ImGui/imgui_draw.s: src/ImGui/imgui_draw.cpp.s

.PHONY : src/ImGui/imgui_draw.s

# target to generate assembly for a file
src/ImGui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_draw.cpp.s
.PHONY : src/ImGui/imgui_draw.cpp.s

src/ImGui/imgui_impl_glfw.o: src/ImGui/imgui_impl_glfw.cpp.o

.PHONY : src/ImGui/imgui_impl_glfw.o

# target to build an object file
src/ImGui/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_impl_glfw.cpp.o
.PHONY : src/ImGui/imgui_impl_glfw.cpp.o

src/ImGui/imgui_impl_glfw.i: src/ImGui/imgui_impl_glfw.cpp.i

.PHONY : src/ImGui/imgui_impl_glfw.i

# target to preprocess a source file
src/ImGui/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_impl_glfw.cpp.i
.PHONY : src/ImGui/imgui_impl_glfw.cpp.i

src/ImGui/imgui_impl_glfw.s: src/ImGui/imgui_impl_glfw.cpp.s

.PHONY : src/ImGui/imgui_impl_glfw.s

# target to generate assembly for a file
src/ImGui/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_impl_glfw.cpp.s
.PHONY : src/ImGui/imgui_impl_glfw.cpp.s

src/ImGui/imgui_impl_opengl3.o: src/ImGui/imgui_impl_opengl3.cpp.o

.PHONY : src/ImGui/imgui_impl_opengl3.o

# target to build an object file
src/ImGui/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_impl_opengl3.cpp.o
.PHONY : src/ImGui/imgui_impl_opengl3.cpp.o

src/ImGui/imgui_impl_opengl3.i: src/ImGui/imgui_impl_opengl3.cpp.i

.PHONY : src/ImGui/imgui_impl_opengl3.i

# target to preprocess a source file
src/ImGui/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_impl_opengl3.cpp.i
.PHONY : src/ImGui/imgui_impl_opengl3.cpp.i

src/ImGui/imgui_impl_opengl3.s: src/ImGui/imgui_impl_opengl3.cpp.s

.PHONY : src/ImGui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/ImGui/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_impl_opengl3.cpp.s
.PHONY : src/ImGui/imgui_impl_opengl3.cpp.s

src/ImGui/imgui_widgets.o: src/ImGui/imgui_widgets.cpp.o

.PHONY : src/ImGui/imgui_widgets.o

# target to build an object file
src/ImGui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_widgets.cpp.o
.PHONY : src/ImGui/imgui_widgets.cpp.o

src/ImGui/imgui_widgets.i: src/ImGui/imgui_widgets.cpp.i

.PHONY : src/ImGui/imgui_widgets.i

# target to preprocess a source file
src/ImGui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_widgets.cpp.i
.PHONY : src/ImGui/imgui_widgets.cpp.i

src/ImGui/imgui_widgets.s: src/ImGui/imgui_widgets.cpp.s

.PHONY : src/ImGui/imgui_widgets.s

# target to generate assembly for a file
src/ImGui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ImGui/imgui_widgets.cpp.s
.PHONY : src/ImGui/imgui_widgets.cpp.s

src/Material.o: src/Material.cpp.o

.PHONY : src/Material.o

# target to build an object file
src/Material.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Material.cpp.o
.PHONY : src/Material.cpp.o

src/Material.i: src/Material.cpp.i

.PHONY : src/Material.i

# target to preprocess a source file
src/Material.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Material.cpp.i
.PHONY : src/Material.cpp.i

src/Material.s: src/Material.cpp.s

.PHONY : src/Material.s

# target to generate assembly for a file
src/Material.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Material.cpp.s
.PHONY : src/Material.cpp.s

src/Mesh.o: src/Mesh.cpp.o

.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i

.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s

.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/ObjLoader.o: src/ObjLoader.cpp.o

.PHONY : src/ObjLoader.o

# target to build an object file
src/ObjLoader.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ObjLoader.cpp.o
.PHONY : src/ObjLoader.cpp.o

src/ObjLoader.i: src/ObjLoader.cpp.i

.PHONY : src/ObjLoader.i

# target to preprocess a source file
src/ObjLoader.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ObjLoader.cpp.i
.PHONY : src/ObjLoader.cpp.i

src/ObjLoader.s: src/ObjLoader.cpp.s

.PHONY : src/ObjLoader.s

# target to generate assembly for a file
src/ObjLoader.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/ObjLoader.cpp.s
.PHONY : src/ObjLoader.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/stb_image.o: src/stb_image.cpp.o

.PHONY : src/stb_image.o

# target to build an object file
src/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/stb_image.cpp.o
.PHONY : src/stb_image.cpp.o

src/stb_image.i: src/stb_image.cpp.i

.PHONY : src/stb_image.i

# target to preprocess a source file
src/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/stb_image.cpp.i
.PHONY : src/stb_image.cpp.i

src/stb_image.s: src/stb_image.cpp.s

.PHONY : src/stb_image.s

# target to generate assembly for a file
src/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/RenderEngine.dir/build.make CMakeFiles/RenderEngine.dir/src/stb_image.cpp.s
.PHONY : src/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... RenderEngine"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... boing"
	@echo "... gears"
	@echo "... heightmap"
	@echo "... sharing"
	@echo "... particles"
	@echo "... simple"
	@echo "... splitview"
	@echo "... offscreen"
	@echo "... wave"
	@echo "... triangle-vulkan"
	@echo "... tearing"
	@echo "... title"
	@echo "... opacity"
	@echo "... clipboard"
	@echo "... msaa"
	@echo "... glfwinfo"
	@echo "... iconify"
	@echo "... reopen"
	@echo "... gamma"
	@echo "... monitors"
	@echo "... windows"
	@echo "... timeout"
	@echo "... inputlag"
	@echo "... threads"
	@echo "... cursor"
	@echo "... empty"
	@echo "... icon"
	@echo "... events"
	@echo "... joysticks"
	@echo "... glad"
	@echo "... IrrXML"
	@echo "... assimp"
	@echo "... assimp_cmd"
	@echo "... unit"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Controls.o"
	@echo "... src/Controls.i"
	@echo "... src/Controls.s"
	@echo "... src/Cube.o"
	@echo "... src/Cube.i"
	@echo "... src/Cube.s"
	@echo "... src/CubeMap.o"
	@echo "... src/CubeMap.i"
	@echo "... src/CubeMap.s"
	@echo "... src/Group.o"
	@echo "... src/Group.i"
	@echo "... src/Group.s"
	@echo "... src/ImGui/imgui.o"
	@echo "... src/ImGui/imgui.i"
	@echo "... src/ImGui/imgui.s"
	@echo "... src/ImGui/imgui_demo.o"
	@echo "... src/ImGui/imgui_demo.i"
	@echo "... src/ImGui/imgui_demo.s"
	@echo "... src/ImGui/imgui_draw.o"
	@echo "... src/ImGui/imgui_draw.i"
	@echo "... src/ImGui/imgui_draw.s"
	@echo "... src/ImGui/imgui_impl_glfw.o"
	@echo "... src/ImGui/imgui_impl_glfw.i"
	@echo "... src/ImGui/imgui_impl_glfw.s"
	@echo "... src/ImGui/imgui_impl_opengl3.o"
	@echo "... src/ImGui/imgui_impl_opengl3.i"
	@echo "... src/ImGui/imgui_impl_opengl3.s"
	@echo "... src/ImGui/imgui_widgets.o"
	@echo "... src/ImGui/imgui_widgets.i"
	@echo "... src/ImGui/imgui_widgets.s"
	@echo "... src/Material.o"
	@echo "... src/Material.i"
	@echo "... src/Material.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/ObjLoader.o"
	@echo "... src/ObjLoader.i"
	@echo "... src/ObjLoader.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/stb_image.o"
	@echo "... src/stb_image.i"
	@echo "... src/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

